-- Run after 20260922023000_phase2_lms_curriculum.sql.
BEGIN;
CREATE TABLE IF NOT EXISTS public.lms_teaching_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,course_id uuid NOT NULL REFERENCES public.lms_courses(id) ON DELETE CASCADE,curriculum_unit_id uuid REFERENCES public.lms_curriculum_units(id) ON DELETE SET NULL,plan_type text NOT NULL CHECK(plan_type IN('scheme','lesson')),title text NOT NULL,week_number integer,lesson_date date,objectives jsonb NOT NULL DEFAULT'[]'::jsonb,activities text,resources text,assessment text,status text NOT NULL DEFAULT'draft' CHECK(status IN('draft','submitted','approved','changes_requested')),author_id uuid NOT NULL REFERENCES auth.users(id),reviewer_id uuid REFERENCES auth.users(id),review_note text,submitted_at timestamptz,reviewed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(char_length(title) BETWEEN 1 AND 200),CHECK(week_number IS NULL OR week_number BETWEEN 1 AND 53),CHECK(jsonb_typeof(objectives)='array' AND jsonb_array_length(objectives) BETWEEN 1 AND 50),CHECK(activities IS NULL OR char_length(activities)<=10000),CHECK(resources IS NULL OR char_length(resources)<=5000),CHECK(assessment IS NULL OR char_length(assessment)<=5000),CHECK(review_note IS NULL OR char_length(review_note)<=3000));
CREATE INDEX IF NOT EXISTS idx_teaching_plans_course ON public.lms_teaching_plans(organization_id,course_id,status,updated_at DESC);
ALTER TABLE public.lms_teaching_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS teaching_plans_read ON public.lms_teaching_plans;
CREATE POLICY teaching_plans_read ON public.lms_teaching_plans FOR SELECT USING(organization_id=public.current_user_org_id() AND(public.is_org_admin(organization_id) OR public.phase1_teacher_course_scope(course_id)));
DROP POLICY IF EXISTS teaching_plans_write ON public.lms_teaching_plans;
CREATE POLICY teaching_plans_write ON public.lms_teaching_plans FOR ALL USING(organization_id=public.current_user_org_id() AND(public.is_org_admin(organization_id) OR(author_id=auth.uid() AND public.phase1_teacher_course_scope(course_id)))) WITH CHECK(organization_id=public.current_user_org_id() AND(public.is_org_admin(organization_id) OR(author_id=auth.uid() AND public.phase1_teacher_course_scope(course_id))));
CREATE OR REPLACE FUNCTION public.phase2_save_teaching_plan(p_plan_id uuid,p_course_id uuid,p_curriculum_unit_id uuid,p_plan_type text,p_title text,p_week_number integer,p_lesson_date date,p_objectives jsonb,p_activities text,p_resources text,p_assessment text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_org uuid:=public.current_user_org_id();v_id uuid;v_status text;v_author uuid;
BEGIN
 IF auth.uid() IS NULL OR v_org IS NULL THEN RAISE EXCEPTION'Authentication required';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.lms_courses WHERE id=p_course_id AND organization_id=v_org FOR UPDATE) OR NOT(public.is_org_admin(v_org) OR public.phase1_teacher_course_scope(p_course_id)) THEN RAISE EXCEPTION'Not authorized for course';END IF;
 IF p_plan_type NOT IN('scheme','lesson') THEN RAISE EXCEPTION'Invalid plan type';END IF;
 IF char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION'Title must be 1 to 200 characters';END IF;
 IF p_objectives IS NULL OR jsonb_typeof(p_objectives)<>'array' OR jsonb_array_length(p_objectives) NOT BETWEEN 1 AND 50 THEN RAISE EXCEPTION'Plan requires 1 to 50 objectives';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(p_objectives)x WHERE char_length(btrim(x)) NOT BETWEEN 1 AND 1000) THEN RAISE EXCEPTION'Each objective must be 1 to 1000 characters';END IF;
 IF p_curriculum_unit_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.lms_curriculum_units WHERE id=p_curriculum_unit_id AND course_id=p_course_id AND organization_id=v_org) THEN RAISE EXCEPTION'Curriculum unit does not belong to course';END IF;
 IF p_plan_id IS NULL THEN INSERT INTO public.lms_teaching_plans(organization_id,course_id,curriculum_unit_id,plan_type,title,week_number,lesson_date,objectives,activities,resources,assessment,author_id) VALUES(v_org,p_course_id,p_curriculum_unit_id,p_plan_type,btrim(p_title),p_week_number,p_lesson_date,p_objectives,nullif(btrim(coalesce(p_activities,'')),''),nullif(btrim(coalesce(p_resources,'')),''),nullif(btrim(coalesce(p_assessment,'')),''),auth.uid()) RETURNING id INTO v_id;
 ELSE SELECT id,status,author_id INTO v_id,v_status,v_author FROM public.lms_teaching_plans WHERE id=p_plan_id AND organization_id=v_org AND course_id=p_course_id FOR UPDATE;IF v_id IS NULL OR(v_author<>auth.uid() AND NOT public.is_org_admin(v_org))THEN RAISE EXCEPTION'Plan not found or not editable';END IF;IF v_status NOT IN('draft','changes_requested')THEN RAISE EXCEPTION'Only draft or returned plans can be edited';END IF;UPDATE public.lms_teaching_plans SET curriculum_unit_id=p_curriculum_unit_id,plan_type=p_plan_type,title=btrim(p_title),week_number=p_week_number,lesson_date=p_lesson_date,objectives=p_objectives,activities=nullif(btrim(coalesce(p_activities,'')),''),resources=nullif(btrim(coalesce(p_resources,'')),''),assessment=nullif(btrim(coalesce(p_assessment,'')),''),updated_at=now() WHERE id=v_id;END IF;
 RETURN v_id;
END $$;
CREATE OR REPLACE FUNCTION public.phase2_transition_teaching_plan(p_plan_id uuid,p_action text,p_note text DEFAULT NULL) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_org uuid:=public.current_user_org_id();v_plan public.lms_teaching_plans%ROWTYPE;
BEGIN SELECT*INTO v_plan FROM public.lms_teaching_plans WHERE id=p_plan_id AND organization_id=v_org FOR UPDATE;IF v_plan.id IS NULL THEN RAISE EXCEPTION'Plan not found';END IF;
 IF p_action='submit' THEN IF v_plan.author_id<>auth.uid() OR v_plan.status NOT IN('draft','changes_requested')THEN RAISE EXCEPTION'Plan cannot be submitted';END IF;UPDATE public.lms_teaching_plans SET status='submitted',submitted_at=now(),review_note=NULL,updated_at=now()WHERE id=p_plan_id;
 ELSIF p_action IN('approve','request_changes')THEN IF NOT public.is_org_admin(v_org) OR v_plan.status<>'submitted'THEN RAISE EXCEPTION'Admin review of a submitted plan is required';END IF;IF p_action='request_changes'AND btrim(coalesce(p_note,''))=''THEN RAISE EXCEPTION'Review note required';END IF;UPDATE public.lms_teaching_plans SET status=CASE WHEN p_action='approve'THEN'approved'ELSE'changes_requested'END,reviewer_id=auth.uid(),review_note=nullif(btrim(coalesce(p_note,'')),''),reviewed_at=now(),updated_at=now()WHERE id=p_plan_id;
 ELSE RAISE EXCEPTION'Invalid transition';END IF;RETURN p_action;END $$;
REVOKE ALL ON FUNCTION public.phase2_save_teaching_plan(uuid,uuid,uuid,text,text,integer,date,jsonb,text,text,text)FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.phase2_save_teaching_plan(uuid,uuid,uuid,text,text,integer,date,jsonb,text,text,text)TO authenticated;
REVOKE ALL ON FUNCTION public.phase2_transition_teaching_plan(uuid,text,text)FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.phase2_transition_teaching_plan(uuid,text,text)TO authenticated;
COMMIT;
